Web/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MySqlApp.Models;

namespace Web.Controllers
{
    public class CarController : Controller
    {
        private readonly AutoRepairShopContext db = new AutoRepairShopContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View(db.Cars.ToList());
        }

        [HttpGet]
        public ActionResult CarSearch(string search)
        {
            var cars = db.Cars.Where(c => c.Brand.ToLower().Contains(search.ToLower())).ToList();
            return PartialView("Search", cars);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var car = db.Cars.Find(id);
            if (car == null)
                return HttpNotFound();

            return View(car);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Car car)
        {
            if (!ModelState.IsValid)
                return View(car);

            db.Cars.Add(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var car = db.Cars.Find(id);
            if (car == null)
                return HttpNotFound();

            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var car = db.Cars.Find(id);
            if (car == null)
                return HttpNotFound();

            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/MechanicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MySqlApp.Models;

namespace Web.Controllers
{
    public class MechanicController : Controller
    {
        private readonly AutoRepairShopContext db = new AutoRepairShopContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View(db.AutoMechanics.ToList());
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var autoMechanic = db.AutoMechanics.Find(id);
            if (autoMechanic == null)
                return HttpNotFound();

            return View(autoMechanic);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AutoMechanic autoMechanic)
        {
            if (ModelState.IsValid)
            {
                db.AutoMechanics.Add(autoMechanic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(autoMechanic);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var autoMechanic = db.AutoMechanics.Find(id);
            if (autoMechanic == null)
                return HttpNotFound();

            return View(autoMechanic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName,Salary,Category,PersonnelNumber")] AutoMechanic autoMechanic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autoMechanic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(autoMechanic);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var autoMechanic = db.AutoMechanics.Find(id);
            if (autoMechanic == null)
                return HttpNotFound();

            return View(autoMechanic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var autoMechanic = db.AutoMechanics.Find(id);
            db.AutoMechanics.Remove(autoMechanic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Works", "Index", "works", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Auto mechanics", "Index", "Mechanic")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>